[package]
authors = ["Maurice Kayser"]
edition = "2018"
keywords = ["bit", "bitfield", "bitfields", "bitflag", "bitflags", "bitmask", "field", "fields", "flag", "flags", "mask"]
license = "MIT/Apache-2.0"
name = "bitfield"
readme = "README.md"
version = "1.4.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"
quote = "1.0.7"
syn = "1.0.44"

[dev-dependencies]
trybuild = "1.0.35"

[dev-dependencies.proc-macro2]
version = "1.0.24"
features = [ "span-locations" ]