[package]
authors = ["Maurice.Kayser"]
keywords = ["bit", "bitfield", "bitfields", "bitflag", "bitflags", "bitmask", "field", "fields", "flag", "flags", "mask"]
license = "MIT/Apache-2.0"
name = "bitfield"
readme = "README.md"
version = "1.0.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.3.8"
quote = "0.5.2"
syn = "0.13.7"
synom = "0.11.3"