[package]
authors = ["Maurice Kayser"]
edition = "2021"
keywords = ["bit", "bitfield", "bitfields", "bitflag", "bitflags", "bitmask", "field", "fields", "flag", "flags", "mask"]
license = "MIT/Apache-2.0"
name = "bitfield"
readme = "README.md"
version = "1.7.4"

[lib]
proc-macro = true

[dependencies]
bitfield-impl = { git = "https://github.com/MauriceKayser/rs-bitfield-impl", rev = "7f41e91e76db6014bdef845821cfa8266e3be4af" }
proc-macro2 = "1.0.43"
quote = "1.0.21"
syn = "1.0.99"

[dev-dependencies]
trybuild = "1.0.64"

[dev-dependencies.proc-macro2]
version = "1.0.43"
features = [ "span-locations" ]