[package]
authors = ["Maurice.Kayser"]
keywords = ["bit", "bitfield", "bitfields", "bitflag", "bitflags", "bitmask", "field", "fields", "flag", "flags", "mask"]
license = "MIT/Apache-2.0"
name = "bitfield"
readme = "README.md"
version = "0.1.0"

[dependencies]
interpolate_idents = "*"
num = "*"